//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixCSV.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FixCSV.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InputFileName.
        /// </summary>
        internal static string CMD_ARG_INPUT_FILENAME {
            get {
                return ResourceManager.GetString("CMD_ARG_INPUT_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewlineReplacementToken.
        /// </summary>
        internal static string CMD_ARG_NEWLINE_REPL_TOKEN {
            get {
                return ResourceManager.GetString("CMD_ARG_NEWLINE_REPL_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FATAL EXCEPTION: Position index exceeds end of file{2}                 Position Index     = {0}{2}                 Characters in File = {1}{2}.
        /// </summary>
        internal static string ERRMSG_BAD_POSITION_INDEX {
            get {
                return ResourceManager.GetString("ERRMSG_BAD_POSITION_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FATAL EXCEPTION: Unbalanced Left Guard Character found{3}                 Left Guard Position = {0}{3}                 Position Index      = {1}{3}                 Characters in File  = {2}{3}.
        /// </summary>
        internal static string ERRMSG_MISSING_RIGHT_GUARD {
            get {
                return ResourceManager.GetString("ERRMSG_MISSING_RIGHT_GUARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .BACKUP.
        /// </summary>
        internal static string MSG_BACKUP_FILE_EXTENSION {
            get {
                return ResourceManager.GetString("MSG_BACKUP_FILE_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A previous backup was created by renaming the original. Details are above..
        /// </summary>
        internal static string MSG_ERROR_BACKUP_OF_BACKUP {
            get {
                return ResourceManager.GetString("MSG_ERROR_BACKUP_OF_BACKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file canot be found or is inaccessible in the current security context..
        /// </summary>
        internal static string MSG_ERROR_FILE_TO_PROCESS_NOT_FOUND {
            get {
                return ResourceManager.GetString("MSG_ERROR_FILE_TO_PROCESS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the file to process was omitted..
        /// </summary>
        internal static string MSG_ERROR_FILE_TO_PROCESS_OMITTED {
            get {
                return ResourceManager.GetString("MSG_ERROR_FILE_TO_PROCESS_OMITTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The label (the first row) of the input file is invalid..
        /// </summary>
        internal static string MSG_ERROR_INVALID_LABEL {
            get {
                return ResourceManager.GetString("MSG_ERROR_INVALID_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A run-time exception has occurred..
        /// </summary>
        internal static string MSG_ERROR_RUNTIME_EXCEPTION {
            get {
                return ResourceManager.GetString("MSG_ERROR_RUNTIME_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following files will be processed.{2}    RFC 4180 Compliant Text File = {0}{2}    Backup of Input File         = {1}{2}    The backup file will be created.{2}.
        /// </summary>
        internal static string MSG_INFO_INPUT_FILENAME {
            get {
                return ResourceManager.GetString("MSG_INFO_INPUT_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input File Details.
        /// </summary>
        internal static string MSG_INPUT_FILE_DETAILS {
            get {
                return ResourceManager.GetString("MSG_INPUT_FILE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {4}Input File:  CR Count = {0}{4}             LF Count = {1}{4}Output File: CR Count = {2}{4}             LF Count = {3}{4}.
        /// </summary>
        internal static string MSG_LINE_BREAK_COUNTS_IN_AND_OUT {
            get {
                return ResourceManager.GetString("MSG_LINE_BREAK_COUNTS_IN_AND_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutputFile Details.
        /// </summary>
        internal static string MSG_OUTPUT_FILE_DETAILS {
            get {
                return ResourceManager.GetString("MSG_OUTPUT_FILE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output file is new, and will be created..
        /// </summary>
        internal static string MSG_OUTPUT_FILE_IS_NEW {
            get {
                return ResourceManager.GetString("MSG_OUTPUT_FILE_IS_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While processing record {0}, an {1} exception occurred.{3}    Original exception message: {2}{3}    Additional details are preserved in the inner exception..
        /// </summary>
        internal static string MSG_PROCESSING_EXCEPTION {
            get {
                return ResourceManager.GetString("MSG_PROCESSING_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} records processed.
        /// </summary>
        internal static string MSG_PROGRESS {
            get {
                return ResourceManager.GetString("MSG_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}{0} quirky line endings were found and fixed.{1}.
        /// </summary>
        internal static string MSG_QUIRKS_REPORT {
            get {
                return ResourceManager.GetString("MSG_QUIRKS_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {3}Processing completed.{3}    Total records processed = {0}{3}    Records with extra tabs = {1}{3}    Well formed records     = {2}{3}{3}.
        /// </summary>
        internal static string MSG_SUMMARY {
            get {
                return ResourceManager.GetString("MSG_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}Minimum command line:{1}{1}{0} InputFileName=CSVFileName{1}where CSVFileName = Name of CSV to process{1}.
        /// </summary>
        internal static string MSG_SYNTAX_HELP {
            get {
                return ResourceManager.GetString("MSG_SYNTAX_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Warning: Record # {1} contains unexpected TAB characters in its DATA.{4}         Contents: {2}{4}         Each will be replaced with a {3} literal.{4}.
        /// </summary>
        internal static string MSG_UNEXPECTED_TABS {
            get {
                return ResourceManager.GetString("MSG_UNEXPECTED_TABS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A backup of this file exists, and is being renamed.{2}    Original Name = {0}{2}    Revised Name  = {1}{2}.
        /// </summary>
        internal static string MSG_WARNING_BACKUP_FILE_EXISTS {
            get {
                return ResourceManager.GetString("MSG_WARNING_BACKUP_FILE_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NBSP.
        /// </summary>
        internal static string NEWLINE_REPL_TOKEN_NBSP {
            get {
                return ResourceManager.GetString("NEWLINE_REPL_TOKEN_NBSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPACE.
        /// </summary>
        internal static string NEWLINE_REPL_TOKEN_SPACE {
            get {
                return ResourceManager.GetString("NEWLINE_REPL_TOKEN_SPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {TAB}.
        /// </summary>
        internal static string TAB_REPL_TOKEN {
            get {
                return ResourceManager.GetString("TAB_REPL_TOKEN", resourceCulture);
            }
        }
    }
}
